# Generated by Django 5.0.1 on 2024-01-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_output',
            options={'verbose_name': 'DB_output'},
        ),
    ]
